# 基本設定
title: Your Site Title
baseurl: "/pastries_website"  # 你的 repository 名稱
url: "https://ileneh889.github.io"

# Build settings
markdown: kramdown
remote_theme: pages-themes/primer@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Liquid 設定
liquid:
  error_mode: warn
  strict_filters: false

# 目錄設定
include:
  - bootstrap-5.1.1
  - css
  - scss
  - img

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

# Jekyll 設定
safe: true
lsi: false
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
